Config:
    AWS_PROFILE: default  # Name of your AWS profile from .aws/credentials
    DESTINATION_NAME: AssetTrackerUplink  # Sidewalk destination used for uplink traffic routing
    HARDWARE_PLATFORM: NORDIC  # Available values: NORDIC, TI, SILABS or ALL
    MFG_ADDRESS: "0xd0000" # mfg page location in device flash 
Outputs:
    DEVICE_PROFILE_ID: 8a0285d4-8ed6-4119-abf8-716207151e8b
_Paths:
    PROVISION_SCRIPT_DIR: tools/provision

